CREATE TABLE meter_data (
	meter_data_id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	meter_number varchar(250) NOT NULL,
	business_partner_id varchar(250) NOT NULL,
	connection_ean_code varchar(250) NOT NULL,
	brand public.brand_enum NOT NULL,
	grid_company_code varchar(250) NOT NULL,
	oda_code varchar(250) NOT NULL,
	smart_collectable public.smart_collectable_enum NOT NULL,
	division public.division_enum NOT NULL,
	sjv1 float8 NULL,
	sjv2 float8 NULL,
	installation varchar(250) not null,
	move_in_date timestamp NOT NULL,
	move_out_date timestamp NOT NULL,
	row_create_datetime timestamp NOT null,
);